"use client";
import { useCallback, useEffect, useState } from "react";

type TrackData = { order: { id:string; status:string; delivery_address:string }; delivery?: { status:string; pickup_address:string; dropoff_address:string; distance_km:number; current_lat?:number; current_lng?:number; location_updated_at?:number }; events: { event_type:string; label:string; created_at:number }[]; courier?: { name:string; rating:number; vehicle:string }; vendor:{name:string} };
const steps = ["accepted","preparing","picked_up","on_the_way","delivered"];

export default function TrackingClient({ orderId }: { orderId:string }) {
  const [data,setData]=useState<TrackData|null>(null); const [error,setError]=useState(""); const [copied,setCopied]=useState(false);
  const load=useCallback(()=>fetch(`/api/track/${encodeURIComponent(orderId)}`,{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error("not found");setData(await r.json())}).catch(()=>setError("We couldn’t find that order.")),[orderId]);
  useEffect(()=>{load();const timer=window.setInterval(load,10000);return()=>window.clearInterval(timer)},[load]);
  if(error)return <main className="tracking-page"><TrackHeader/><section className="tracking-error"><span>?</span><h1>Order not found</h1><p>Check the tracking number and try again.</p><a href="/">Return home</a></section></main>;
  if(!data)return <main className="tracking-page"><TrackHeader/><div className="tracking-loading">Locating your delivery…</div></main>;
  const status=data.delivery?.status||data.order.status; const normalized=status==="picked_up"?"on_the_way":status; const active=Math.max(0,steps.indexOf(normalized));
  return <main className="tracking-page"><TrackHeader/><section className="tracking-shell"><div className="tracking-title"><div><p>LIVE ORDER TRACKING</p><h1>Order #{data.order.id}</h1><span>Updates automatically every 10 seconds</span></div><button onClick={async()=>{await navigator.clipboard.writeText(location.href);setCopied(true)}}>{copied?"Link copied ✓":"Share tracking link"}</button></div><div className="tracking-grid"><article className="tracking-map"><div className="track-road a"/><div className="track-road b"/><div className="track-road c"/><div className="track-route"/><span className="track-pin shop">🏪</span><span className="track-pin rider">🛵</span><span className="track-pin destination">⌂</span><div className="eta-card"><small>ESTIMATED ARRIVAL</small><strong>{status==="delivered"?"Delivered":"8–12 min"}</strong><span>{data.delivery?.distance_km||2.4} km remaining</span></div></article><aside className="tracking-panel"><div className="tracking-status"><i/><div><small>{status.replaceAll("_"," ").toUpperCase()}</small><h2>{status==="delivered"?"Your order has arrived.":"Your delivery is moving."}</h2><p>{data.courier?.name||"A rider"} is heading to {data.delivery?.dropoff_address||data.order.delivery_address}.</p></div></div><div className="track-courier"><span>BR</span><div><strong>{data.courier?.name||"Assigning rider"}</strong><small>★ {data.courier?.rating||"—"} · {data.courier?.vehicle||"Courier"}</small></div><button>Message</button></div><div className="timeline">{steps.map((step,i)=><div className={`${i<=active?"done":""} ${i===active?"current":""}`} key={step}><i>{i<active?"✓":""}</i><div><strong>{step.replaceAll("_"," ")}</strong><small>{i<=active?(data.events.find(e=>e.event_type===step)?new Date(data.events.find(e=>e.event_type===step)!.created_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}):"Completed"):"Waiting"}</small></div></div>)}</div><div className="tracking-help"><span>Need help with this order?</span><a href="/signin-with-chatgpt?return_to=%2Fdashboard">Open order support →</a></div></aside></div></section></main>;
}
function TrackHeader(){return <header className="track-header"><a className="brand" href="/"><span className="brandmark">K</span><span>KOLA</span></a><span>Secure live tracking</span><a href="/dashboard">Open Kola</a></header>}
