import Link from "next/link";
import { getChatGPTUser } from "./chatgpt-auth";

export const dynamic = "force-dynamic";

export default async function LandingPage() {
  const user = await getChatGPTUser();
  return <main className="landing">
    <header className="landing-nav"><Link className="brand" href="/"><span className="brandmark">K</span><span>KOLA</span></Link><nav><a href="#how">How it works</a><a href="#logistics">Logistics</a><a href="#business">For business</a></nav><div className="landing-actions"><Link className="text-link" href="/track/KL-2084">Track an order</Link><Link className="primary" href={user ? "/dashboard" : "/signin-with-chatgpt?return_to=%2Fonboarding"}>{user ? "Open Kola" : "Get started"} →</Link></div></header>
    <section className="landing-hero"><div className="hero-copy"><p>CAMEROON COMMERCE, DELIVERED</p><h1>Sell it. Send it.<br/><em>Track every step.</em></h1><span>Kola brings shops, customers, and delivery riders into one reliable order journey—from payment to doorstep.</span><div><Link className="primary hero-button" href={user ? "/dashboard" : "/signin-with-chatgpt?return_to=%2Fonboarding"}>Start with Kola →</Link><Link className="hero-link" href="/track/KL-2084">Track a delivery</Link></div><small>Built for Douala · Yaoundé · Across Cameroon</small></div><div className="hero-scene"><div className="route-card"><p>ORDER #KL-2084</p><strong>Chez Mado → Bonapriso</strong><div className="route-progress"><i/><span/><i/><span/><i/></div><div className="route-labels"><span>Accepted</span><span>Picked up</span><span>8 min away</span></div></div><div className="hero-bike">🛵</div><div className="hero-bubble">💬 <b>Everyone stays connected</b></div></div></section>
    <section className="trust-strip"><span>One order journey</span><b>Mobile Money ready</b><b>Live delivery tracking</b><b>Customer · Vendor · Rider chat</b></section>
    <section className="landing-section" id="how"><p>ONE PLATFORM, THREE EXPERIENCES</p><h2>Commerce that moves together.</h2><div className="role-cards"><article><span>01</span><div>🛍️</div><h3>Customers</h3><p>Discover nearby businesses, order securely, and follow every delivery milestone.</p></article><article><span>02</span><div>🏪</div><h3>Vendors</h3><p>Build a storefront, manage orders, and dispatch reliable riders from one workspace.</p></article><article><span>03</span><div>🛵</div><h3>Riders</h3><p>Accept transparent trips, navigate pickups, communicate, and manage earnings.</p></article></div></section>
    <section className="logistics-section" id="logistics"><div><p>LOGISTICS AT THE CORE</p><h2>The delivery is not an afterthought.</h2><span>Automatic dispatch, visible milestones, proof of delivery, and a shared conversation are part of every order.</span><Link href="/track/KL-2084">See live tracking demo →</Link></div><div className="logistics-map"><div className="map-road one"/><div className="map-road two"/><i className="pin shop">🏪</i><i className="pin bike">🛵</i><i className="pin home">⌂</i><span className="map-route"/></div></section>
    <section className="business-cta" id="business"><p>READY TO MOVE YOUR BUSINESS?</p><h2>Start selling. We’ll help deliver.</h2><Link className="primary hero-button" href={user ? "/dashboard" : "/signin-with-chatgpt?return_to=%2Fonboarding"}>Create your Kola account →</Link></section>
    <footer><span className="brand"><span className="brandmark">K</span><b>KOLA</b></span><p>Made for Cameroon · English & Français</p><Link href="/track/KL-2084">Track an order</Link></footer>
  </main>;
}
